# Generated by Django 3.1.4 on 2021-01-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspaper',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
