# Generated by Django 3.1.4 on 2021-01-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_newspaper_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspaper',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
