# Generated by Django 3.1.4 on 2021-01-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_newspaper_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='endDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='startDate',
            field=models.DateField(null=True),
        ),
    ]
