# Generated by Django 3.1.4 on 2021-01-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210104_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
